#!/usr/bin/env python3
"""Generate AudioSplit.xcodeproj for the menu bar app target.

The SwiftPM package stays the source of truth for the engine, the CLI harnesses
and the tests — `swift test` must keep working from a terminal. The Xcode project
exists to build, sign and ship the .app, and consumes the engine as a local
package product so there is exactly one copy of the engine sources.

Regenerate with:  python3 Scripts/generate-xcodeproj.py
"""
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROJECT = ROOT / "AudioSplit.xcodeproj"
APP_SOURCES = ROOT / "Sources" / "AudioSplitApp"
BUNDLE_ID = "com.audiosplit.AudioSplit"
DEPLOYMENT_TARGET = "14.4"


def oid(*parts: str) -> str:
    """Stable 24-hex object id, so regenerating produces a minimal diff."""
    return hashlib.sha256("::".join(parts).encode()).hexdigest()[:24].upper()


def swift_sources() -> list[pathlib.Path]:
    return sorted(p for p in APP_SOURCES.rglob("*.swift"))


def main() -> int:
    sources = swift_sources()
    if not sources:
        print(f"no Swift sources under {APP_SOURCES}", file=sys.stderr)
        return 1

    ids = {
        "project": oid("project"),
        "target": oid("target", "AudioSplit"),
        "product": oid("product", "AudioSplit.app"),
        "mainGroup": oid("group", "main"),
        "productsGroup": oid("group", "Products"),
        "appGroup": oid("group", "AudioSplitApp"),
        "uiGroup": oid("group", "UI"),
        "sourcesPhase": oid("phase", "sources"),
        "frameworksPhase": oid("phase", "frameworks"),
        "resourcesPhase": oid("phase", "resources"),
        "projectConfigList": oid("configlist", "project"),
        "targetConfigList": oid("configlist", "target"),
        "projectDebug": oid("config", "project", "Debug"),
        "projectRelease": oid("config", "project", "Release"),
        "targetDebug": oid("config", "target", "Debug"),
        "targetRelease": oid("config", "target", "Release"),
        "packageRef": oid("packageref", "local"),
        "packageProduct": oid("packageproduct", "AudioSplitEngine"),
        "packageProductBuildFile": oid("buildfile", "AudioSplitEngine"),
        "iconRef": oid("fileref", "AppIcon.icns"),
        "iconBuildFile": oid("buildfile", "AppIcon.icns"),
    }

    file_refs, build_files, app_children, ui_children = [], [], [], []
    for source in sources:
        rel = source.relative_to(ROOT).as_posix()
        ref_id = oid("fileref", rel)
        build_id = oid("buildfile", rel)
        file_refs.append(
            f'\t\t{ref_id} /* {source.name} */ = {{isa = PBXFileReference; '
            f'lastKnownFileType = sourcecode.swift; name = "{source.name}"; '
            f'path = "{rel}"; sourceTree = "<group>"; }};'
        )
        build_files.append(
            f'\t\t{build_id} /* {source.name} in Sources */ = {{isa = PBXBuildFile; '
            f'fileRef = {ref_id} /* {source.name} */; }};'
        )
        entry = f"\t\t\t\t{ref_id} /* {source.name} */,"
        (ui_children if source.parent.name == "UI" else app_children).append(entry)

    source_phase_files = "\n".join(
        f'\t\t\t\t{oid("buildfile", p.relative_to(ROOT).as_posix())} /* {p.name} in Sources */,'
        for p in sources
    )

    # The app icon, generated by Scripts/make-icon.swift.
    file_refs.append(
        f'\t\t{ids["iconRef"]} /* AppIcon.icns */ = {{isa = PBXFileReference; '
        f'lastKnownFileType = image.icns; name = "AppIcon.icns"; '
        f'path = "Resources/AppIcon.icns"; sourceTree = "<group>"; }};'
    )
    build_files.append(
        f'\t\t{ids["iconBuildFile"]} /* AppIcon.icns in Resources */ = '
        f'{{isa = PBXBuildFile; fileRef = {ids["iconRef"]} /* AppIcon.icns */; }};'
    )
    app_children.append(f'\t\t\t\t{ids["iconRef"]} /* AppIcon.icns */,')

    plist_ref = oid("fileref", "Info.plist")
    file_refs.append(
        f'\t\t{plist_ref} /* Info.plist */ = {{isa = PBXFileReference; '
        f'lastKnownFileType = text.plist.xml; name = "Info.plist"; '
        f'path = "Sources/AudioSplitApp/Info.plist"; sourceTree = "<group>"; }};'
    )
    app_children.append(f"\t\t\t\t{plist_ref} /* Info.plist */,")

    common_settings = f"""\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;
\t\t\t\tCLANG_ENABLE_MODULES = YES;
\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;
\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;
\t\t\t\tENABLE_HARDENED_RUNTIME = YES;
\t\t\t\tGCC_NO_COMMON_BLOCKS = YES;
\t\t\t\tMACOSX_DEPLOYMENT_TARGET = {DEPLOYMENT_TARGET};
\t\t\t\tSDKROOT = macosx;
\t\t\t\tSWIFT_STRICT_CONCURRENCY = complete;
\t\t\t\tSWIFT_VERSION = 6.0;"""

    target_settings = f"""\t\t\t\tCODE_SIGN_STYLE = Automatic;
\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;
\t\t\t\tCURRENT_PROJECT_VERSION = 4;
\t\t\t\tENABLE_HARDENED_RUNTIME = YES;
\t\t\t\tGENERATE_INFOPLIST_FILE = NO;
\t\t\t\tINFOPLIST_FILE = "Sources/AudioSplitApp/Info.plist";
\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (
\t\t\t\t\t"$(inherited)",
\t\t\t\t\t"@executable_path/../Frameworks",
\t\t\t\t);
\t\t\t\tMARKETING_VERSION = 0.4;
\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = {BUNDLE_ID};
\t\t\t\tPRODUCT_NAME = AudioSplit;
\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;"""

    pbxproj = f"""// !$*UTF8*$!
{{
\tarchiveVersion = 1;
\tclasses = {{
\t}};
\tobjectVersion = 56;
\tobjects = {{

/* Begin PBXBuildFile section */
{chr(10).join(build_files)}
\t\t{ids["packageProductBuildFile"]} /* AudioSplitEngine in Frameworks */ = {{isa = PBXBuildFile; productRef = {ids["packageProduct"]} /* AudioSplitEngine */; }};
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
{chr(10).join(file_refs)}
\t\t{ids["product"]} /* AudioSplit.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = AudioSplit.app; sourceTree = BUILT_PRODUCTS_DIR; }};
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
\t\t{ids["frameworksPhase"]} /* Frameworks */ = {{
\t\t\tisa = PBXFrameworksBuildPhase;
\t\t\tbuildActionMask = 2147483647;
\t\t\tfiles = (
\t\t\t\t{ids["packageProductBuildFile"]} /* AudioSplitEngine in Frameworks */,
\t\t\t);
\t\t\trunOnlyForDeploymentPostprocessing = 0;
\t\t}};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
\t\t{ids["mainGroup"]} = {{
\t\t\tisa = PBXGroup;
\t\t\tchildren = (
\t\t\t\t{ids["appGroup"]} /* AudioSplitApp */,
\t\t\t\t{ids["productsGroup"]} /* Products */,
\t\t\t);
\t\t\tsourceTree = "<group>";
\t\t}};
\t\t{ids["appGroup"]} /* AudioSplitApp */ = {{
\t\t\tisa = PBXGroup;
\t\t\tchildren = (
{chr(10).join(app_children)}
\t\t\t\t{ids["uiGroup"]} /* UI */,
\t\t\t);
\t\t\tname = AudioSplitApp;
\t\t\tsourceTree = "<group>";
\t\t}};
\t\t{ids["uiGroup"]} /* UI */ = {{
\t\t\tisa = PBXGroup;
\t\t\tchildren = (
{chr(10).join(ui_children)}
\t\t\t);
\t\t\tname = UI;
\t\t\tsourceTree = "<group>";
\t\t}};
\t\t{ids["productsGroup"]} /* Products */ = {{
\t\t\tisa = PBXGroup;
\t\t\tchildren = (
\t\t\t\t{ids["product"]} /* AudioSplit.app */,
\t\t\t);
\t\t\tname = Products;
\t\t\tsourceTree = "<group>";
\t\t}};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
\t\t{ids["target"]} /* AudioSplit */ = {{
\t\t\tisa = PBXNativeTarget;
\t\t\tbuildConfigurationList = {ids["targetConfigList"]} /* Build configuration list for PBXNativeTarget "AudioSplit" */;
\t\t\tbuildPhases = (
\t\t\t\t{ids["sourcesPhase"]} /* Sources */,
\t\t\t\t{ids["frameworksPhase"]} /* Frameworks */,
\t\t\t\t{ids["resourcesPhase"]} /* Resources */,
\t\t\t);
\t\t\tbuildRules = (
\t\t\t);
\t\t\tdependencies = (
\t\t\t);
\t\t\tname = AudioSplit;
\t\t\tpackageProductDependencies = (
\t\t\t\t{ids["packageProduct"]} /* AudioSplitEngine */,
\t\t\t);
\t\t\tproductName = AudioSplit;
\t\t\tproductReference = {ids["product"]} /* AudioSplit.app */;
\t\t\tproductType = "com.apple.product-type.application";
\t\t}};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
\t\t{ids["project"]} /* Project object */ = {{
\t\t\tisa = PBXProject;
\t\t\tattributes = {{
\t\t\t\tBuildIndependentTargetsInParallel = 1;
\t\t\t\tLastSwiftUpdateCheck = 1600;
\t\t\t\tLastUpgradeCheck = 1600;
\t\t\t\tTargetAttributes = {{
\t\t\t\t\t{ids["target"]} = {{
\t\t\t\t\t\tCreatedOnToolsVersion = 16.0;
\t\t\t\t\t}};
\t\t\t\t}};
\t\t\t}};
\t\t\tbuildConfigurationList = {ids["projectConfigList"]} /* Build configuration list for PBXProject "AudioSplit" */;
\t\t\tdevelopmentRegion = en;
\t\t\thasScannedForEncodings = 0;
\t\t\tknownRegions = (
\t\t\t\ten,
\t\t\t\tBase,
\t\t\t);
\t\t\tmainGroup = {ids["mainGroup"]};
\t\t\tpackageReferences = (
\t\t\t\t{ids["packageRef"]} /* XCLocalSwiftPackageReference "." */,
\t\t\t);
\t\t\tproductRefGroup = {ids["productsGroup"]} /* Products */;
\t\t\tprojectDirPath = "";
\t\t\tprojectRoot = "";
\t\t\ttargets = (
\t\t\t\t{ids["target"]} /* AudioSplit */,
\t\t\t);
\t\t}};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
\t\t{ids["resourcesPhase"]} /* Resources */ = {{
\t\t\tisa = PBXResourcesBuildPhase;
\t\t\tbuildActionMask = 2147483647;
\t\t\tfiles = (
\t\t\t\t{ids["iconBuildFile"]} /* AppIcon.icns in Resources */,
\t\t\t);
\t\t\trunOnlyForDeploymentPostprocessing = 0;
\t\t}};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
\t\t{ids["sourcesPhase"]} /* Sources */ = {{
\t\t\tisa = PBXSourcesBuildPhase;
\t\t\tbuildActionMask = 2147483647;
\t\t\tfiles = (
{source_phase_files}
\t\t\t);
\t\t\trunOnlyForDeploymentPostprocessing = 0;
\t\t}};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
\t\t{ids["projectDebug"]} /* Debug */ = {{
\t\t\tisa = XCBuildConfiguration;
\t\t\tbuildSettings = {{
{common_settings}
\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;
\t\t\t\tENABLE_TESTABILITY = YES;
\t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;
\t\t\t\tONLY_ACTIVE_ARCH = YES;
\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG $(inherited)";
\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = "-Onone";
\t\t\t}};
\t\t\tname = Debug;
\t\t}};
\t\t{ids["projectRelease"]} /* Release */ = {{
\t\t\tisa = XCBuildConfiguration;
\t\t\tbuildSettings = {{
{common_settings}
\t\t\t\tDEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;
\t\t\t}};
\t\t\tname = Release;
\t\t}};
\t\t{ids["targetDebug"]} /* Debug */ = {{
\t\t\tisa = XCBuildConfiguration;
\t\t\tbuildSettings = {{
{target_settings}
\t\t\t}};
\t\t\tname = Debug;
\t\t}};
\t\t{ids["targetRelease"]} /* Release */ = {{
\t\t\tisa = XCBuildConfiguration;
\t\t\tbuildSettings = {{
{target_settings}
\t\t\t}};
\t\t\tname = Release;
\t\t}};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
\t\t{ids["projectConfigList"]} /* Build configuration list for PBXProject "AudioSplit" */ = {{
\t\t\tisa = XCConfigurationList;
\t\t\tbuildConfigurations = (
\t\t\t\t{ids["projectDebug"]} /* Debug */,
\t\t\t\t{ids["projectRelease"]} /* Release */,
\t\t\t);
\t\t\tdefaultConfigurationIsVisible = 0;
\t\t\tdefaultConfigurationName = Release;
\t\t}};
\t\t{ids["targetConfigList"]} /* Build configuration list for PBXNativeTarget "AudioSplit" */ = {{
\t\t\tisa = XCConfigurationList;
\t\t\tbuildConfigurations = (
\t\t\t\t{ids["targetDebug"]} /* Debug */,
\t\t\t\t{ids["targetRelease"]} /* Release */,
\t\t\t);
\t\t\tdefaultConfigurationIsVisible = 0;
\t\t\tdefaultConfigurationName = Release;
\t\t}};
/* End XCConfigurationList section */

/* Begin XCLocalSwiftPackageReference section */
\t\t{ids["packageRef"]} /* XCLocalSwiftPackageReference "." */ = {{
\t\t\tisa = XCLocalSwiftPackageReference;
\t\t\trelativePath = .;
\t\t}};
/* End XCLocalSwiftPackageReference section */

/* Begin XCSwiftPackageProductDependency section */
\t\t{ids["packageProduct"]} /* AudioSplitEngine */ = {{
\t\t\tisa = XCSwiftPackageProductDependency;
\t\t\tproductName = AudioSplitEngine;
\t\t}};
/* End XCSwiftPackageProductDependency section */
\t}};
\trootObject = {ids["project"]} /* Project object */;
}}
"""

    PROJECT.mkdir(parents=True, exist_ok=True)
    (PROJECT / "project.pbxproj").write_text(pbxproj)
    print(f"generated {PROJECT.relative_to(ROOT)} with {len(sources)} source file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
